import { GridLayout, ListView, ItemSpec, GridUnitType, Color, Button, EventData, TextView, ItemEventData, Screen, Application, Utils } from '@nativescript/core';

export interface CodigosI {
  nombre: string;
  bandera: string;
  name: string;
  nom: string;
  iso2: string;
  iso3: string;
  codigo: string;
}

export let Codigos: Array<CodigosI> = [
  {
    nombre: 'Afganistán',
    name: 'Afghanistan',
    nom: 'Afghanistan',
    iso2: 'AF',
    iso3: 'AFG',
    codigo: '93',
    bandera: 'res://afg',
  },
  {
    nombre: 'Albania',
    name: 'Albania',
    nom: 'Albanie',
    iso2: 'AL',
    iso3: 'ALB',
    codigo: '355',
    bandera: 'res://alb',
  },
  {
    nombre: 'Alemania',
    name: 'Germany',
    nom: 'Allemagne',
    iso2: 'DE',
    iso3: 'DEU',
    codigo: '49',
    bandera: 'res://deu',
  },
  {
    nombre: 'Andorra',
    name: 'Andorra',
    nom: 'Andorra',
    iso2: 'AD',
    iso3: 'AND',
    codigo: '376',
    bandera: 'res://and',
  },
  {
    nombre: 'Angola',
    name: 'Angola',
    nom: 'Angola',
    iso2: 'AO',
    iso3: 'AGO',
    codigo: '244',
    bandera: 'res://ago',
  },
  {
    nombre: 'Anguila',
    name: 'Anguilla',
    nom: 'Anguilla',
    iso2: 'AI',
    iso3: 'AIA',
    codigo: '1 264',
    bandera: 'res://aia',
  },
  {
    nombre: 'Antártida',
    name: 'Antarctica',
    nom: "L'Antarctique",
    iso2: 'AQ',
    iso3: 'ATA',
    codigo: '672',
    bandera: 'res://hmd',
  },
  {
    nombre: 'Antigua y Barbuda',
    name: 'Antigua and Barbuda',
    nom: 'Antigua et Barbuda',
    iso2: 'AG',
    iso3: 'ATG',
    codigo: '1 268',
    bandera: 'res://atg',
  },
  {
    nombre: 'Arabia Saudita',
    name: 'Saudi Arabia',
    nom: 'Arabie Saoudite',
    iso2: 'SA',
    iso3: 'SAU',
    codigo: '966',
    bandera: 'res://sau',
  },
  {
    nombre: 'Argelia',
    name: 'Algeria',
    nom: 'Algérie',
    iso2: 'DZ',
    iso3: 'DZA',
    codigo: '213',
    bandera: 'res://dza',
  },
  {
    nombre: 'Argentina',
    name: 'Argentina',
    nom: 'Argentine',
    iso2: 'AR',
    iso3: 'ARG',
    codigo: '54',
    bandera: 'res://arg',
  },
  {
    nombre: 'Armenia',
    name: 'Armenia',
    nom: "L'Arménie",
    iso2: 'AM',
    iso3: 'ARM',
    codigo: '374',
    bandera: 'res://arm',
  },
  {
    nombre: 'Aruba',
    name: 'Aruba',
    nom: 'Aruba',
    iso2: 'AW',
    iso3: 'ABW',
    codigo: '297',
    bandera: 'res://abw',
  },
  {
    nombre: 'Australia',
    name: 'Australia',
    nom: 'Australie',
    iso2: 'AU',
    iso3: 'AUS',
    codigo: '61',
    bandera: 'res://aus',
  },
  {
    nombre: 'Austria',
    name: 'Austria',
    nom: 'Autriche',
    iso2: 'AT',
    iso3: 'AUT',
    codigo: '43',
    bandera: 'res://aut',
  },
  {
    nombre: 'Azerbaiyán',
    name: 'Azerbaijan',
    nom: "L'Azerbaïdjan",
    iso2: 'AZ',
    iso3: 'AZE',
    codigo: '994',
    bandera: 'res://aze',
  },
  {
    nombre: 'Bélgica',
    name: 'Belgium',
    nom: 'Belgique',
    iso2: 'BE',
    iso3: 'BEL',
    codigo: '32',
    bandera: 'res://bel',
  },
  {
    nombre: 'Bahamas',
    name: 'Bahamas',
    nom: 'Bahamas',
    iso2: 'BS',
    iso3: 'BHS',
    codigo: '1 242',
    bandera: 'res://bhs',
  },
  {
    nombre: 'Bahrein',
    name: 'Bahrain',
    nom: 'Bahreïn',
    iso2: 'BH',
    iso3: 'BHR',
    codigo: '973',
    bandera: 'res://bhr',
  },
  {
    nombre: 'Bangladesh',
    name: 'Bangladesh',
    nom: 'Bangladesh',
    iso2: 'BD',
    iso3: 'BGD',
    codigo: '880',
    bandera: 'res://bgd',
  },
  {
    nombre: 'Barbados',
    name: 'Barbados',
    nom: 'Barbade',
    iso2: 'BB',
    iso3: 'BRB',
    codigo: '1 246',
    bandera: 'res://brb',
  },
  {
    nombre: 'Belice',
    name: 'Belize',
    nom: 'Belize',
    iso2: 'BZ',
    iso3: 'BLZ',
    codigo: '501',
    bandera: 'res://blz',
  },
  {
    nombre: 'Benín',
    name: 'Benin',
    nom: 'Bénin',
    iso2: 'BJ',
    iso3: 'BEN',
    codigo: '229',
    bandera: 'res://ben',
  },
  {
    nombre: 'Bhután',
    name: 'Bhutan',
    nom: 'Le Bhoutan',
    iso2: 'BT',
    iso3: 'BTN',
    codigo: '975',
    bandera: 'res://btn',
  },
  {
    nombre: 'Bielorrusia',
    name: 'Belarus',
    nom: 'Biélorussie',
    iso2: 'BY',
    iso3: 'BLR',
    codigo: '375',
    bandera: 'res://blr',
  },
  {
    nombre: 'Birmania',
    name: 'Myanmar',
    nom: 'Myanmar',
    iso2: 'MM',
    iso3: 'MMR',
    codigo: '95',
    bandera: 'res://mmr',
  },
  {
    nombre: 'Bolivia',
    name: 'Bolivia',
    nom: 'Bolivie',
    iso2: 'BO',
    iso3: 'BOL',
    codigo: '591',
    bandera: 'res://bol',
  },
  {
    nombre: 'Bosnia y Herzegovina',
    name: 'Bosnia and Herzegovina',
    nom: 'Bosnie-Herzégovine',
    iso2: 'BA',
    iso3: 'BIH',
    codigo: '387',
    bandera: 'res://bih',
  },
  {
    nombre: 'Botsuana',
    name: 'Botswana',
    nom: 'Botswana',
    iso2: 'BW',
    iso3: 'BWA',
    codigo: '267',
    bandera: 'res://bwa',
  },
  {
    nombre: 'Brasil',
    name: 'Brazil',
    nom: 'Brésil',
    iso2: 'BR',
    iso3: 'BRA',
    codigo: '55',
    bandera: 'res://bra',
  },
  {
    nombre: 'Brunéi',
    name: 'Brunei',
    nom: 'Brunei',
    iso2: 'BN',
    iso3: 'BRN',
    codigo: '673',
    bandera: 'res://brn',
  },
  {
    nombre: 'Bulgaria',
    name: 'Bulgaria',
    nom: 'Bulgarie',
    iso2: 'BG',
    iso3: 'BGR',
    codigo: '359',
    bandera: 'res://bgr',
  },
  {
    nombre: 'Burkina Faso',
    name: 'Burkina Faso',
    nom: 'Burkina Faso',
    iso2: 'BF',
    iso3: 'BFA',
    codigo: '226',
    bandera: 'res://bfa',
  },
  {
    nombre: 'Burundi',
    name: 'Burundi',
    nom: 'Burundi',
    iso2: 'BI',
    iso3: 'BDI',
    codigo: '257',
    bandera: 'res://bdi',
  },
  {
    nombre: 'Cabo Verde',
    name: 'Cape Verde',
    nom: 'Cap-Vert',
    iso2: 'CV',
    iso3: 'CPV',
    codigo: '238',
    bandera: 'res://cpv',
  },
  {
    nombre: 'Camboya',
    name: 'Cambodia',
    nom: 'Cambodge',
    iso2: 'KH',
    iso3: 'KHM',
    codigo: '855',
    bandera: 'res://khm',
  },
  {
    nombre: 'Camerún',
    name: 'Cameroon',
    nom: 'Cameroun',
    iso2: 'CM',
    iso3: 'CMR',
    codigo: '237',
    bandera: 'res://cmr',
  },
  {
    nombre: 'Canadá',
    name: 'Canada',
    nom: 'Canada',
    iso2: 'CA',
    iso3: 'CAN',
    codigo: '1',
    bandera: 'res://can',
  },
  {
    nombre: 'Chad',
    name: 'Chad',
    nom: 'Tchad',
    iso2: 'TD',
    iso3: 'TCD',
    codigo: '235',
    bandera: 'res://tcd',
  },
  {
    nombre: 'Chile',
    name: 'Chile',
    nom: 'Chili',
    iso2: 'CL',
    iso3: 'CHL',
    codigo: '56',
    bandera: 'res://chl',
  },
  {
    nombre: 'China',
    name: 'China',
    nom: 'Chine',
    iso2: 'CN',
    iso3: 'CHN',
    codigo: '86',
    bandera: 'res://chn',
  },
  {
    nombre: 'Chipre',
    name: 'Cyprus',
    nom: 'Chypre',
    iso2: 'CY',
    iso3: 'CYP',
    codigo: '357',
    bandera: 'res://cyp',
  },
  {
    nombre: 'Ciudad del Vaticano',
    name: 'Vatican City State',
    nom: 'Cité du Vatican',
    iso2: 'VA',
    iso3: 'VAT',
    codigo: '39',
    bandera: 'res://vat',
  },
  {
    nombre: 'Colombia',
    name: 'Colombia',
    nom: 'Colombie',
    iso2: 'CO',
    iso3: 'COL',
    codigo: '57',
    bandera: 'res://col',
  },
  {
    nombre: 'Comoras',
    name: 'Comoros',
    nom: 'Comores',
    iso2: 'KM',
    iso3: 'COM',
    codigo: '269',
    bandera: 'res://com',
  },
  {
    nombre: 'República del Congo',
    name: 'Republic of the Congo',
    nom: 'République du Congo',
    iso2: 'CG',
    iso3: 'COG',
    codigo: '242',
    bandera: 'res://cog',
  },
  {
    nombre: 'República Democrática del Congo',
    name: 'Democratic Republic of the Congo',
    nom: 'République démocratique du Congo',
    iso2: 'CD',
    iso3: 'COD',
    codigo: '243',
    bandera: 'res://cod',
  },
  {
    nombre: 'Corea del Norte',
    name: 'North Korea',
    nom: 'Corée du Nord',
    iso2: 'KP',
    iso3: 'PRK',
    codigo: '850',
    bandera: 'res://prk',
  },
  {
    nombre: 'Corea del Sur',
    name: 'South Korea',
    nom: 'Corée du Sud',
    iso2: 'KR',
    iso3: 'KOR',
    codigo: '82',
    bandera: 'res://kor',
  },
  {
    nombre: 'Costa de Marfil',
    name: 'Ivory Coast',
    nom: "Côte-d'Ivoire",
    iso2: 'CI',
    iso3: 'CIV',
    codigo: '225',
    bandera: 'res://civ',
  },
  {
    nombre: 'Costa Rica',
    name: 'Costa Rica',
    nom: 'Costa Rica',
    iso2: 'CR',
    iso3: 'CRI',
    codigo: '506',
    bandera: 'res://cri',
  },
  {
    nombre: 'Croacia',
    name: 'Croatia',
    nom: 'Croatie',
    iso2: 'HR',
    iso3: 'HRV',
    codigo: '385',
    bandera: 'res://hrv',
  },
  {
    nombre: 'Cuba',
    name: 'Cuba',
    nom: 'Cuba',
    iso2: 'CU',
    iso3: 'CUB',
    codigo: '53',
    bandera: 'res://cub',
  },
  {
    nombre: 'Curazao',
    name: 'Curaçao',
    nom: 'Curaçao',
    iso2: 'CW',
    iso3: 'CWU',
    codigo: '5999',
    bandera: 'res://cuw',
  },
  {
    nombre: 'Dinamarca',
    name: 'Denmark',
    nom: 'Danemark',
    iso2: 'DK',
    iso3: 'DNK',
    codigo: '45',
    bandera: 'res://dnk',
  },
  {
    nombre: 'Dominica',
    name: 'Dominica',
    nom: 'Dominique',
    iso2: 'DM',
    iso3: 'DMA',
    codigo: '1 767',
    bandera: 'res://dma',
  },
  {
    nombre: 'Ecuador',
    name: 'Ecuador',
    nom: 'Equateur',
    iso2: 'EC',
    iso3: 'ECU',
    codigo: '593',
    bandera: 'res://ecu',
  },
  {
    nombre: 'Egipto',
    name: 'Egypt',
    nom: 'Egypte',
    iso2: 'EG',
    iso3: 'EGY',
    codigo: '20',
    bandera: 'res://egy',
  },
  {
    nombre: 'El Salvador',
    name: 'El Salvador',
    nom: 'El Salvador',
    iso2: 'SV',
    iso3: 'SLV',
    codigo: '503',
    bandera: 'res://slv',
  },
  {
    nombre: 'Emiratos Árabes Unidos',
    name: 'United Arab Emirates',
    nom: 'Emirats Arabes Unis',
    iso2: 'AE',
    iso3: 'ARE',
    codigo: '971',
    bandera: 'res://are',
  },
  {
    nombre: 'Eritrea',
    name: 'Eritrea',
    nom: 'Erythrée',
    iso2: 'ER',
    iso3: 'ERI',
    codigo: '291',
    bandera: 'res://eri',
  },
  {
    nombre: 'Eslovaquia',
    name: 'Slovakia',
    nom: 'Slovaquie',
    iso2: 'SK',
    iso3: 'SVK',
    codigo: '421',
    bandera: 'res://svk',
  },
  {
    nombre: 'Eslovenia',
    name: 'Slovenia',
    nom: 'Slovénie',
    iso2: 'SI',
    iso3: 'SVN',
    codigo: '386',
    bandera: 'res://svn',
  },
  {
    nombre: 'España',
    name: 'Spain',
    nom: 'Espagne',
    iso2: 'ES',
    iso3: 'ESP',
    codigo: '34',
    bandera: 'res://esp',
  },
  {
    nombre: 'Estados Unidos de América',
    name: 'United States of America',
    nom: "États-Unis d'Amérique",
    iso2: 'US',
    iso3: 'USA',
    codigo: '1',
    bandera: 'res://usa',
  },
  {
    nombre: 'Estonia',
    name: 'Estonia',
    nom: "L'Estonie",
    iso2: 'EE',
    iso3: 'EST',
    codigo: '372',
    bandera: 'res://est',
  },
  {
    nombre: 'Etiopía',
    name: 'Ethiopia',
    nom: 'Ethiopie',
    iso2: 'ET',
    iso3: 'ETH',
    codigo: '251',
    bandera: 'res://eth',
  },
  {
    nombre: 'Filipinas',
    name: 'Philippines',
    nom: 'Philippines',
    iso2: 'PH',
    iso3: 'PHL',
    codigo: '63',
    bandera: 'res://phl',
  },
  {
    nombre: 'Finlandia',
    name: 'Finland',
    nom: 'Finlande',
    iso2: 'FI',
    iso3: 'FIN',
    codigo: '358',
    bandera: 'res://fin',
  },
  {
    nombre: 'Fiyi',
    name: 'Fiji',
    nom: 'Fidji',
    iso2: 'FJ',
    iso3: 'FJI',
    codigo: '679',
    bandera: 'res://fji',
  },
  {
    nombre: 'Francia',
    name: 'France',
    nom: 'France',
    iso2: 'FR',
    iso3: 'FRA',
    codigo: '33',
    bandera: 'res://fra',
  },
  {
    nombre: 'Gabón',
    name: 'Gabon',
    nom: 'Gabon',
    iso2: 'GA',
    iso3: 'GAB',
    codigo: '241',
    bandera: 'res://gab',
  },
  {
    nombre: 'Gambia',
    name: 'Gambia',
    nom: 'Gambie',
    iso2: 'GM',
    iso3: 'GMB',
    codigo: '220',
    bandera: 'res://gmb',
  },
  {
    nombre: 'Georgia',
    name: 'Georgia',
    nom: 'Géorgie',
    iso2: 'GE',
    iso3: 'GEO',
    codigo: '995',
    bandera: 'res://geo',
  },
  {
    nombre: 'Ghana',
    name: 'Ghana',
    nom: 'Ghana',
    iso2: 'GH',
    iso3: 'GHA',
    codigo: '233',
    bandera: 'res://gha',
  },
  {
    nombre: 'Gibraltar',
    name: 'Gibraltar',
    nom: 'Gibraltar',
    iso2: 'GI',
    iso3: 'GIB',
    codigo: '350',
    bandera: 'res://gib',
  },
  {
    nombre: 'Granada',
    name: 'Grenada',
    nom: 'Grenade',
    iso2: 'GD',
    iso3: 'GRD',
    codigo: '1 473',
    bandera: 'res://grd',
  },
  {
    nombre: 'Grecia',
    name: 'Greece',
    nom: 'Grèce',
    iso2: 'GR',
    iso3: 'GRC',
    codigo: '30',
    bandera: 'res://grc',
  },
  {
    nombre: 'Groenlandia',
    name: 'Greenland',
    nom: 'Groenland',
    iso2: 'GL',
    iso3: 'GRL',
    codigo: '299',
    bandera: 'res://grl',
  },
  {
    nombre: 'Guadalupe',
    name: 'Guadeloupe',
    nom: 'Guadeloupe',
    iso2: 'GP',
    iso3: 'GLP',
    codigo: '590',
    bandera: 'res://glp',
  },
  {
    nombre: 'Guam',
    name: 'Guam',
    nom: 'Guam',
    iso2: 'GU',
    iso3: 'GUM',
    codigo: '1 671',
    bandera: 'res://gum',
  },
  {
    nombre: 'Guatemala',
    name: 'Guatemala',
    nom: 'Guatemala',
    iso2: 'GT',
    iso3: 'GTM',
    codigo: '502',
    bandera: 'res://gtm',
  },
  {
    nombre: 'Guayana Francesa',
    name: 'French Guiana',
    nom: 'Guyane française',
    iso2: 'GF',
    iso3: 'GUF',
    codigo: '594',
    bandera: 'res://guf',
  },
  {
    nombre: 'Guernsey',
    name: 'Guernsey',
    nom: 'Guernesey',
    iso2: 'GG',
    iso3: 'GGY',
    codigo: '44',
    bandera: 'res://ggy',
  },
  {
    nombre: 'Guinea',
    name: 'Guinea',
    nom: 'Guinée',
    iso2: 'GN',
    iso3: 'GIN',
    codigo: '224',
    bandera: 'res://gin',
  },
  {
    nombre: 'Guinea Ecuatorial',
    name: 'Equatorial Guinea',
    nom: 'Guinée Equatoriale',
    iso2: 'GQ',
    iso3: 'GNQ',
    codigo: '240',
    bandera: 'res://gnq',
  },
  {
    nombre: 'Guinea-Bissau',
    name: 'Guinea-Bissau',
    nom: 'Guinée-Bissau',
    iso2: 'GW',
    iso3: 'GNB',
    codigo: '245',
    bandera: 'res://gnb',
  },
  {
    nombre: 'Guyana',
    name: 'Guyana',
    nom: 'Guyane',
    iso2: 'GY',
    iso3: 'GUY',
    codigo: '592',
    bandera: 'res://guy',
  },
  {
    nombre: 'Haití',
    name: 'Haiti',
    nom: 'Haïti',
    iso2: 'HT',
    iso3: 'HTI',
    codigo: '509',
    bandera: 'res://hti',
  },
  {
    nombre: 'Honduras',
    name: 'Honduras',
    nom: 'Honduras',
    iso2: 'HN',
    iso3: 'HND',
    codigo: '504',
    bandera: 'res://hnd',
  },
  {
    nombre: 'Hong kong',
    name: 'Hong Kong',
    nom: 'Hong Kong',
    iso2: 'HK',
    iso3: 'HKG',
    codigo: '852',
    bandera: 'res://hkg',
  },
  {
    nombre: 'Hungría',
    name: 'Hungary',
    nom: 'Hongrie',
    iso2: 'HU',
    iso3: 'HUN',
    codigo: '36',
    bandera: 'res://hun',
  },
  {
    nombre: 'India',
    name: 'India',
    nom: 'Inde',
    iso2: 'IN',
    iso3: 'IND',
    codigo: '91',
    bandera: 'res://ind',
  },
  {
    nombre: 'Indonesia',
    name: 'Indonesia',
    nom: 'Indonésie',
    iso2: 'ID',
    iso3: 'IDN',
    codigo: '62',
    bandera: 'res://idn',
  },
  {
    nombre: 'Irán',
    name: 'Iran',
    nom: 'Iran',
    iso2: 'IR',
    iso3: 'IRN',
    codigo: '98',
    bandera: 'res://irn',
  },
  {
    nombre: 'Irak',
    name: 'Iraq',
    nom: 'Irak',
    iso2: 'IQ',
    iso3: 'IRQ',
    codigo: '964',
    bandera: 'res://irq',
  },
  {
    nombre: 'Irlanda',
    name: 'Ireland',
    nom: 'Irlande',
    iso2: 'IE',
    iso3: 'IRL',
    codigo: '353',
    bandera: 'res://irl',
  },
  {
    nombre: 'Isla Bouvet',
    name: 'Bouvet Island',
    nom: 'Bouvet Island',
    iso2: 'BV',
    iso3: 'BVT',
    codigo: '',
    bandera: 'res://bvt',
  },
  {
    nombre: 'Isla de Man',
    name: 'Isle of Man',
    nom: 'Ile de Man',
    iso2: 'IM',
    iso3: 'IMN',
    codigo: '44',
    bandera: 'res://imn',
  },
  {
    nombre: 'Isla de Navidad',
    name: 'Christmas Island',
    nom: 'Christmas Island',
    iso2: 'CX',
    iso3: 'CXR',
    codigo: '61',
    bandera: 'res://cxr',
  },
  {
    nombre: 'Isla Norfolk',
    name: 'Norfolk Island',
    nom: 'Île de Norfolk',
    iso2: 'NF',
    iso3: 'NFK',
    codigo: '672',
    bandera: 'res://nfk',
  },
  {
    nombre: 'Islandia',
    name: 'Iceland',
    nom: 'Islande',
    iso2: 'IS',
    iso3: 'ISL',
    codigo: '354',
    bandera: 'res://isl',
  },
  {
    nombre: 'Islas Bermudas',
    name: 'Bermuda Islands',
    nom: 'Bermudes',
    iso2: 'BM',
    iso3: 'BMU',
    codigo: '1 441',
    bandera: 'res://bmu',
  },
  {
    nombre: 'Islas Caimán',
    name: 'Cayman Islands',
    nom: 'Iles Caïmans',
    iso2: 'KY',
    iso3: 'CYM',
    codigo: '1 345',
    bandera: 'res://cym',
  },
  {
    nombre: 'Islas Cocos (Keeling)',
    name: 'Cocos (Keeling) Islands',
    nom: 'Cocos (Keeling',
    iso2: 'CC',
    iso3: 'CCK',
    codigo: '61',
    bandera: 'res://cck',
  },
  {
    nombre: 'Islas Cook',
    name: 'Cook Islands',
    nom: 'Iles Cook',
    iso2: 'CK',
    iso3: 'COK',
    codigo: '682',
    bandera: 'res://cok',
  },
  {
    nombre: 'Islas de Åland',
    name: 'Åland Islands',
    nom: 'Îles Åland',
    iso2: 'AX',
    iso3: 'ALA',
    codigo: '358',
    bandera: 'res://ala',
  },
  {
    nombre: 'Islas Feroe',
    name: 'Faroe Islands',
    nom: 'Iles Féro',
    iso2: 'FO',
    iso3: 'FRO',
    codigo: '298',
    bandera: 'res://fro',
  },
  {
    nombre: 'Islas Georgias del Sur y Sandwich del Sur',
    name: 'South Georgia and the South Sandwich Islands',
    nom: 'Géorgie du Sud et les Îles Sandwich du Sud',
    iso2: 'GS',
    iso3: 'SGS',
    codigo: '500',
    bandera: 'res://sgs',
  },
  {
    nombre: 'Islas Heard y McDonald',
    name: 'Heard Island and McDonald Islands',
    nom: 'Les îles Heard et McDonald',
    iso2: 'HM',
    iso3: 'HMD',
    codigo: '',
    bandera: 'res://hmd',
  },
  {
    nombre: 'Islas Maldivas',
    name: 'Maldives',
    nom: 'Maldives',
    iso2: 'MV',
    iso3: 'MDV',
    codigo: '960',
    bandera: 'res://mdv',
  },
  {
    nombre: 'Islas Malvinas',
    name: 'Falkland Islands (Malvinas)',
    nom: 'Iles Falkland (Malvinas',
    iso2: 'FK',
    iso3: 'FLK',
    codigo: '500',
    bandera: 'res://flk',
  },
  {
    nombre: 'Islas Marianas del Norte',
    name: 'Northern Mariana Islands',
    nom: 'Iles Mariannes du Nord',
    iso2: 'MP',
    iso3: 'MNP',
    codigo: '1 670',
    bandera: 'res://mnp',
  },
  {
    nombre: 'Islas Marshall',
    name: 'Marshall Islands',
    nom: 'Iles Marshall',
    iso2: 'MH',
    iso3: 'MHL',
    codigo: '692',
    bandera: 'res://mhl',
  },
  {
    nombre: 'Islas Pitcairn',
    name: 'Pitcairn Islands',
    nom: 'Iles Pitcairn',
    iso2: 'PN',
    iso3: 'PCN',
    codigo: '870',
    bandera: 'res://pcn',
  },
  {
    nombre: 'Islas Salomón',
    name: 'Solomon Islands',
    nom: 'Iles Salomon',
    iso2: 'SB',
    iso3: 'SLB',
    codigo: '677',
    bandera: 'res://slb',
  },
  {
    nombre: 'Islas Turcas y Caicos',
    name: 'Turks and Caicos Islands',
    nom: 'Iles Turques et Caïques',
    iso2: 'TC',
    iso3: 'TCA',
    codigo: '1 649',
    bandera: 'res://tca',
  },
  {
    nombre: 'Islas Ultramarinas Menores de Estados Unidos',
    name: 'United States Minor Outlying Islands',
    nom: 'États-Unis Îles mineures éloignées',
    iso2: 'UM',
    iso3: 'UMI',
    codigo: '246',
    bandera: 'res://umi',
  },
  {
    nombre: 'Islas Vírgenes Británicas',
    name: 'Virgin Islands',
    nom: 'Iles Vierges',
    iso2: 'VG',
    iso3: 'VGB',
    codigo: '1 284',
    bandera: 'res://vgb',
  },
  {
    nombre: 'Islas Vírgenes de los Estados Unidos',
    name: 'United States Virgin Islands',
    nom: 'Îles Vierges américaines',
    iso2: 'VI',
    iso3: 'VIR',
    codigo: '1 340',
    bandera: 'res://vir',
  },
  {
    nombre: 'Israel',
    name: 'Israel',
    nom: 'Israël',
    iso2: 'IL',
    iso3: 'ISR',
    codigo: '972',
    bandera: 'res://isr',
  },
  {
    nombre: 'Italia',
    name: 'Italy',
    nom: 'Italie',
    iso2: 'IT',
    iso3: 'ITA',
    codigo: '39',
    bandera: 'res://ita',
  },
  {
    nombre: 'Jamaica',
    name: 'Jamaica',
    nom: 'Jamaïque',
    iso2: 'JM',
    iso3: 'JAM',
    codigo: '1 876',
    bandera: 'res://jam',
  },
  {
    nombre: 'Japón',
    name: 'Japan',
    nom: 'Japon',
    iso2: 'JP',
    iso3: 'JPN',
    codigo: '81',
    bandera: 'res://jpn',
  },
  {
    nombre: 'Jersey',
    name: 'Jersey',
    nom: 'Maillot',
    iso2: 'JE',
    iso3: 'JEY',
    codigo: '44',
    bandera: 'res://jey',
  },
  {
    nombre: 'Jordania',
    name: 'Jordan',
    nom: 'Jordan',
    iso2: 'JO',
    iso3: 'JOR',
    codigo: '962',
    bandera: 'res://jor',
  },
  {
    nombre: 'Kazajistán',
    name: 'Kazakhstan',
    nom: 'Le Kazakhstan',
    iso2: 'KZ',
    iso3: 'KAZ',
    codigo: '7',
    bandera: 'res://kaz',
  },
  {
    nombre: 'Kenia',
    name: 'Kenya',
    nom: 'Kenya',
    iso2: 'KE',
    iso3: 'KEN',
    codigo: '254',
    bandera: 'res://ken',
  },
  {
    nombre: 'Kirguistán',
    name: 'Kyrgyzstan',
    nom: 'Kirghizstan',
    iso2: 'KG',
    iso3: 'KGZ',
    codigo: '996',
    bandera: 'res://kgz',
  },
  {
    nombre: 'Kiribati',
    name: 'Kiribati',
    nom: 'Kiribati',
    iso2: 'KI',
    iso3: 'KIR',
    codigo: '686',
    bandera: 'res://kir',
  },
  {
    nombre: 'Kuwait',
    name: 'Kuwait',
    nom: 'Koweït',
    iso2: 'KW',
    iso3: 'KWT',
    codigo: '965',
    bandera: 'res://kwt',
  },
  {
    nombre: 'Líbano',
    name: 'Lebanon',
    nom: 'Liban',
    iso2: 'LB',
    iso3: 'LBN',
    codigo: '961',
    bandera: 'res://lbn',
  },
  {
    nombre: 'Laos',
    name: 'Laos',
    nom: 'Laos',
    iso2: 'LA',
    iso3: 'LAO',
    codigo: '856',
    bandera: 'res://lao',
  },
  {
    nombre: 'Lesoto',
    name: 'Lesotho',
    nom: 'Lesotho',
    iso2: 'LS',
    iso3: 'LSO',
    codigo: '266',
    bandera: 'res://lso',
  },
  {
    nombre: 'Letonia',
    name: 'Latvia',
    nom: 'La Lettonie',
    iso2: 'LV',
    iso3: 'LVA',
    codigo: '371',
    bandera: 'res://lva',
  },
  {
    nombre: 'Liberia',
    name: 'Liberia',
    nom: 'Liberia',
    iso2: 'LR',
    iso3: 'LBR',
    codigo: '231',
    bandera: 'res://lbr',
  },
  {
    nombre: 'Libia',
    name: 'Libya',
    nom: 'Libye',
    iso2: 'LY',
    iso3: 'LBY',
    codigo: '218',
    bandera: 'res://lby',
  },
  {
    nombre: 'Liechtenstein',
    name: 'Liechtenstein',
    nom: 'Liechtenstein',
    iso2: 'LI',
    iso3: 'LIE',
    codigo: '423',
    bandera: 'res://lie',
  },
  {
    nombre: 'Lituania',
    name: 'Lithuania',
    nom: 'La Lituanie',
    iso2: 'LT',
    iso3: 'LTU',
    codigo: '370',
    bandera: 'res://ltu',
  },
  {
    nombre: 'Luxemburgo',
    name: 'Luxembourg',
    nom: 'Luxembourg',
    iso2: 'LU',
    iso3: 'LUX',
    codigo: '352',
    bandera: 'res://lux',
  },
  {
    nombre: 'México',
    name: 'Mexico',
    nom: 'Mexique',
    iso2: 'MX',
    iso3: 'MEX',
    codigo: '52',
    bandera: 'res://mex',
  },
  {
    nombre: 'Mónaco',
    name: 'Monaco',
    nom: 'Monaco',
    iso2: 'MC',
    iso3: 'MCO',
    codigo: '377',
    bandera: 'res://mco',
  },
  {
    nombre: 'Macao',
    name: 'Macao',
    nom: 'Macao',
    iso2: 'MO',
    iso3: 'MAC',
    codigo: '853',
    bandera: 'res://mac',
  },
  {
    nombre: 'Macedônia',
    name: 'Macedonia',
    nom: 'Macédoine',
    iso2: 'MK',
    iso3: 'MKD',
    codigo: '389',
    bandera: 'res://mkd',
  },
  {
    nombre: 'Madagascar',
    name: 'Madagascar',
    nom: 'Madagascar',
    iso2: 'MG',
    iso3: 'MDG',
    codigo: '261',
    bandera: 'res://mdg',
  },
  {
    nombre: 'Malasia',
    name: 'Malaysia',
    nom: 'Malaisie',
    iso2: 'MY',
    iso3: 'MYS',
    codigo: '60',
    bandera: 'res://mys',
  },
  {
    nombre: 'Malawi',
    name: 'Malawi',
    nom: 'Malawi',
    iso2: 'MW',
    iso3: 'MWI',
    codigo: '265',
    bandera: 'res://mwi',
  },
  {
    nombre: 'Mali',
    name: 'Mali',
    nom: 'Mali',
    iso2: 'ML',
    iso3: 'MLI',
    codigo: '223',
    bandera: 'res://mli',
  },
  {
    nombre: 'Malta',
    name: 'Malta',
    nom: 'Malte',
    iso2: 'MT',
    iso3: 'MLT',
    codigo: '356',
    bandera: 'res://mlt',
  },
  {
    nombre: 'Marruecos',
    name: 'Morocco',
    nom: 'Maroc',
    iso2: 'MA',
    iso3: 'MAR',
    codigo: '212',
    bandera: 'res://mar',
  },
  {
    nombre: 'Martinica',
    name: 'Martinique',
    nom: 'Martinique',
    iso2: 'MQ',
    iso3: 'MTQ',
    codigo: '596',
    bandera: 'res://mtq',
  },
  {
    nombre: 'Mauricio',
    name: 'Mauritius',
    nom: 'Iles Maurice',
    iso2: 'MU',
    iso3: 'MUS',
    codigo: '230',
    bandera: 'res://mus',
  },
  {
    nombre: 'Mauritania',
    name: 'Mauritania',
    nom: 'Mauritanie',
    iso2: 'MR',
    iso3: 'MRT',
    codigo: '222',
    bandera: 'res://mrt',
  },
  {
    nombre: 'Mayotte',
    name: 'Mayotte',
    nom: 'Mayotte',
    iso2: 'YT',
    iso3: 'MYT',
    codigo: '262',
    bandera: 'res://myt',
  },
  {
    nombre: 'Micronesia',
    name: 'Estados Federados de',
    nom: 'Federados Estados de',
    iso2: 'FM',
    iso3: 'FSM',
    codigo: '691',
    bandera: 'res://fsm',
  },
  {
    nombre: 'Moldavia',
    name: 'Moldova',
    nom: 'Moldavie',
    iso2: 'MD',
    iso3: 'MDA',
    codigo: '373',
    bandera: 'res://mda',
  },
  {
    nombre: 'Mongolia',
    name: 'Mongolia',
    nom: 'Mongolie',
    iso2: 'MN',
    iso3: 'MNG',
    codigo: '976',
    bandera: 'res://mng',
  },
  {
    nombre: 'Montenegro',
    name: 'Montenegro',
    nom: 'Monténégro',
    iso2: 'ME',
    iso3: 'MNE',
    codigo: '382',
    bandera: 'res://mne',
  },
  {
    nombre: 'Montserrat',
    name: 'Montserrat',
    nom: 'Montserrat',
    iso2: 'MS',
    iso3: 'MSR',
    codigo: '1 664',
    bandera: 'res://msr',
  },
  {
    nombre: 'Mozambique',
    name: 'Mozambique',
    nom: 'Mozambique',
    iso2: 'MZ',
    iso3: 'MOZ',
    codigo: '258',
    bandera: 'res://moz',
  },
  {
    nombre: 'Namibia',
    name: 'Namibia',
    nom: 'Namibie',
    iso2: 'NA',
    iso3: 'NAM',
    codigo: '264',
    bandera: 'res://nam',
  },
  {
    nombre: 'Nauru',
    name: 'Nauru',
    nom: 'Nauru',
    iso2: 'NR',
    iso3: 'NRU',
    codigo: '674',
    bandera: 'res://nru',
  },
  {
    nombre: 'Nepal',
    name: 'Nepal',
    nom: 'Népal',
    iso2: 'NP',
    iso3: 'NPL',
    codigo: '977',
    bandera: 'res://npl',
  },
  {
    nombre: 'Nicaragua',
    name: 'Nicaragua',
    nom: 'Nicaragua',
    iso2: 'NI',
    iso3: 'NIC',
    codigo: '505',
    bandera: 'res://nic',
  },
  {
    nombre: 'Niger',
    name: 'Niger',
    nom: 'Niger',
    iso2: 'NE',
    iso3: 'NER',
    codigo: '227',
    bandera: 'res://ner',
  },
  {
    nombre: 'Nigeria',
    name: 'Nigeria',
    nom: 'Nigeria',
    iso2: 'NG',
    iso3: 'NGA',
    codigo: '234',
    bandera: 'res://nga',
  },
  {
    nombre: 'Niue',
    name: 'Niue',
    nom: 'Niou',
    iso2: 'NU',
    iso3: 'NIU',
    codigo: '683',
    bandera: 'res://niu',
  },
  {
    nombre: 'Noruega',
    name: 'Norway',
    nom: 'Norvège',
    iso2: 'NO',
    iso3: 'NOR',
    codigo: '47',
    bandera: 'res://nor',
  },
  {
    nombre: 'Nueva Caledonia',
    name: 'New Caledonia',
    nom: 'Nouvelle-Calédonie',
    iso2: 'NC',
    iso3: 'NCL',
    codigo: '687',
    bandera: 'res://ncl',
  },
  {
    nombre: 'Nueva Zelanda',
    name: 'New Zealand',
    nom: 'Nouvelle-Zélande',
    iso2: 'NZ',
    iso3: 'NZL',
    codigo: '64',
    bandera: 'res://nzl',
  },
  {
    nombre: 'Omán',
    name: 'Oman',
    nom: 'Oman',
    iso2: 'OM',
    iso3: 'OMN',
    codigo: '968',
    bandera: 'res://omn',
  },
  {
    nombre: 'Países Bajos',
    name: 'Netherlands',
    nom: 'Pays-Bas',
    iso2: 'NL',
    iso3: 'NLD',
    codigo: '31',
    bandera: 'res://nld',
  },
  {
    nombre: 'Pakistán',
    name: 'Pakistan',
    nom: 'Pakistan',
    iso2: 'PK',
    iso3: 'PAK',
    codigo: '92',
    bandera: 'res://pak',
  },
  {
    nombre: 'Palau',
    name: 'Palau',
    nom: 'Palau',
    iso2: 'PW',
    iso3: 'PLW',
    codigo: '680',
    bandera: 'res://plw',
  },
  {
    nombre: 'Palestina',
    name: 'Palestine',
    nom: 'La Palestine',
    iso2: 'PS',
    iso3: 'PSE',
    codigo: '970',
    bandera: 'res://pse',
  },
  {
    nombre: 'Panamá',
    name: 'Panama',
    nom: 'Panama',
    iso2: 'PA',
    iso3: 'PAN',
    codigo: '507',
    bandera: 'res://pan',
  },
  {
    nombre: 'Papúa Nueva Guinea',
    name: 'Papua New Guinea',
    nom: 'Papouasie-Nouvelle-Guinée',
    iso2: 'PG',
    iso3: 'PNG',
    codigo: '675',
    bandera: 'res://png',
  },
  {
    nombre: 'Paraguay',
    name: 'Paraguay',
    nom: 'Paraguay',
    iso2: 'PY',
    iso3: 'PRY',
    codigo: '595',
    bandera: 'res://pry',
  },
  {
    nombre: 'Perú',
    name: 'Peru',
    nom: 'Pérou',
    iso2: 'PE',
    iso3: 'PER',
    codigo: '51',
    bandera: 'res://per',
  },
  {
    nombre: 'Polinesia Francesa',
    name: 'French Polynesia',
    nom: 'Polynésie française',
    iso2: 'PF',
    iso3: 'PYF',
    codigo: '689',
    bandera: 'res://pyf',
  },
  {
    nombre: 'Polonia',
    name: 'Poland',
    nom: 'Pologne',
    iso2: 'PL',
    iso3: 'POL',
    codigo: '48',
    bandera: 'res://pol',
  },
  {
    nombre: 'Portugal',
    name: 'Portugal',
    nom: 'Portugal',
    iso2: 'PT',
    iso3: 'PRT',
    codigo: '351',
    bandera: 'res://prt',
  },
  {
    nombre: 'Puerto Rico',
    name: 'Puerto Rico',
    nom: 'Porto Rico',
    iso2: 'PR',
    iso3: 'PRI',
    codigo: '1',
    bandera: 'res://pri',
  },
  {
    nombre: 'Qatar',
    name: 'Qatar',
    nom: 'Qatar',
    iso2: 'QA',
    iso3: 'QAT',
    codigo: '974',
    bandera: 'res://qat',
  },
  {
    nombre: 'Reino Unido',
    name: 'United Kingdom',
    nom: 'Royaume-Uni',
    iso2: 'GB',
    iso3: 'GBR',
    codigo: '44',
    bandera: 'res://gbr',
  },
  {
    nombre: 'República Centroafricana',
    name: 'Central African Republic',
    nom: 'République Centrafricaine',
    iso2: 'CF',
    iso3: 'CAF',
    codigo: '236',
    bandera: 'res://caf',
  },
  {
    nombre: 'República Checa',
    name: 'Czech Republic',
    nom: 'République Tchèque',
    iso2: 'CZ',
    iso3: 'CZE',
    codigo: '420',
    bandera: 'res://cze',
  },
  {
    nombre: 'República Dominicana',
    name: 'Dominican Republic',
    nom: 'République Dominicaine',
    iso2: 'DO',
    iso3: 'DOM',
    codigo: '1 809',
    bandera: 'res://dom',
  },
  {
    nombre: 'República de Sudán del Sur',
    name: 'South Sudan',
    nom: 'Soudan du Sud',
    iso2: 'SS',
    iso3: 'SSD',
    codigo: '211',
    bandera: 'res://ssd',
  },
  {
    nombre: 'Reunión',
    name: 'Réunion',
    nom: 'Réunion',
    iso2: 'RE',
    iso3: 'REU',
    codigo: '262',
    bandera: 'res://reu',
  },
  {
    nombre: 'Ruanda',
    name: 'Rwanda',
    nom: 'Rwanda',
    iso2: 'RW',
    iso3: 'RWA',
    codigo: '250',
    bandera: 'res://rwa',
  },
  {
    nombre: 'Rumanía',
    name: 'Romania',
    nom: 'Roumanie',
    iso2: 'RO',
    iso3: 'ROU',
    codigo: '40',
    bandera: 'res://rou',
  },
  {
    nombre: 'Rusia',
    name: 'Russia',
    nom: 'La Russie',
    iso2: 'RU',
    iso3: 'RUS',
    codigo: '7',
    bandera: 'res://rus',
  },
  {
    nombre: 'Sahara Occidental',
    name: 'Western Sahara',
    nom: 'Sahara Occidental',
    iso2: 'EH',
    iso3: 'ESH',
    codigo: '212',
    bandera: 'res://so',
  },
  {
    nombre: 'Samoa',
    name: 'Samoa',
    nom: 'Samoa',
    iso2: 'WS',
    iso3: 'WSM',
    codigo: '685',
    bandera: 'res://wsm',
  },
  {
    nombre: 'Samoa Americana',
    name: 'American Samoa',
    nom: 'Les Samoa américaines',
    iso2: 'AS',
    iso3: 'ASM',
    codigo: '1 684',
    bandera: 'res://asm',
  },
  {
    nombre: 'San Bartolomé',
    name: 'Saint Barthélemy',
    nom: 'Saint-Barthélemy',
    iso2: 'BL',
    iso3: 'BLM',
    codigo: '590',
    bandera: 'res://blm',
  },
  {
    nombre: 'San Cristóbal y Nieves',
    name: 'Saint Kitts and Nevis',
    nom: 'Saint Kitts et Nevis',
    iso2: 'KN',
    iso3: 'KNA',
    codigo: '1 869',
    bandera: 'res://kna',
  },
  {
    nombre: 'San Marino',
    name: 'San Marino',
    nom: 'San Marino',
    iso2: 'SM',
    iso3: 'SMR',
    codigo: '378',
    bandera: 'res://smr',
  },
  {
    nombre: 'San Martín (Francia)',
    name: 'Saint Martin (French part)',
    nom: 'Saint-Martin (partie française)',
    iso2: 'MF',
    iso3: 'MAF',
    codigo: '1 599',
    bandera: 'res://maf',
  },
  {
    nombre: 'San Pedro y Miquelón',
    name: 'Saint Pierre and Miquelon',
    nom: 'Saint-Pierre-et-Miquelon',
    iso2: 'PM',
    iso3: 'SPM',
    codigo: '508',
    bandera: 'res://spm',
  },
  {
    nombre: 'San Vicente y las Granadinas',
    name: 'Saint Vincent and the Grenadines',
    nom: 'Saint-Vincent et Grenadines',
    iso2: 'VC',
    iso3: 'VCT',
    codigo: '1 784',
    bandera: 'res://vct',
  },
  {
    nombre: 'Santa Elena',
    name: 'Ascensión y Tristán de Acuña',
    nom: 'Ascensión y Tristan de Acuña',
    iso2: 'SH',
    iso3: 'SHN',
    codigo: '290',
    bandera: 'res://se',
  },
  {
    nombre: 'Santa Lucía',
    name: 'Saint Lucia',
    nom: 'Sainte-Lucie',
    iso2: 'LC',
    iso3: 'LCA',
    codigo: '1 758',
    bandera: 'res://lca',
  },
  {
    nombre: 'Santo Tomé y Príncipe',
    name: 'Sao Tome and Principe',
    nom: 'Sao Tomé et Principe',
    iso2: 'ST',
    iso3: 'STP',
    codigo: '239',
    bandera: 'res://stp',
  },
  {
    nombre: 'Senegal',
    name: 'Senegal',
    nom: 'Sénégal',
    iso2: 'SN',
    iso3: 'SEN',
    codigo: '221',
    bandera: 'res://sen',
  },
  {
    nombre: 'Serbia',
    name: 'Serbia',
    nom: 'Serbie',
    iso2: 'RS',
    iso3: 'SRB',
    codigo: '381',
    bandera: 'res://srb',
  },
  {
    nombre: 'Seychelles',
    name: 'Seychelles',
    nom: 'Les Seychelles',
    iso2: 'SC',
    iso3: 'SYC',
    codigo: '248',
    bandera: 'res://syc',
  },
  {
    nombre: 'Sierra Leona',
    name: 'Sierra Leone',
    nom: 'Sierra Leone',
    iso2: 'SL',
    iso3: 'SLE',
    codigo: '232',
    bandera: 'res://sle',
  },
  {
    nombre: 'Singapur',
    name: 'Singapore',
    nom: 'Singapour',
    iso2: 'SG',
    iso3: 'SGP',
    codigo: '65',
    bandera: 'res://sgp',
  },
  {
    nombre: 'Sint Maarten',
    name: 'Sint Maarten',
    nom: 'Saint-Martin',
    iso2: 'SX',
    iso3: 'SMX',
    codigo: '1 721',
    bandera: 'res://sxm',
  },
  {
    nombre: 'Siria',
    name: 'Syria',
    nom: 'Syrie',
    iso2: 'SY',
    iso3: 'SYR',
    codigo: '963',
    bandera: 'res://syr',
  },
  {
    nombre: 'Somalia',
    name: 'Somalia',
    nom: 'Somalie',
    iso2: 'SO',
    iso3: 'SOM',
    codigo: '252',
    bandera: 'res://som',
  },
  {
    nombre: 'Sri lanka',
    name: 'Sri Lanka',
    nom: 'Sri Lanka',
    iso2: 'LK',
    iso3: 'LKA',
    codigo: '94',
    bandera: 'res://lka',
  },
  {
    nombre: 'Sudáfrica',
    name: 'South Africa',
    nom: 'Afrique du Sud',
    iso2: 'ZA',
    iso3: 'ZAF',
    codigo: '27',
    bandera: 'res://zaf',
  },
  {
    nombre: 'Sudán',
    name: 'Sudan',
    nom: 'Soudan',
    iso2: 'SD',
    iso3: 'SDN',
    codigo: '249',
    bandera: 'res://sdn',
  },
  {
    nombre: 'Suecia',
    name: 'Sweden',
    nom: 'Suède',
    iso2: 'SE',
    iso3: 'SWE',
    codigo: '46',
    bandera: 'res://swe',
  },
  {
    nombre: 'Suiza',
    name: 'Switzerland',
    nom: 'Suisse',
    iso2: 'CH',
    iso3: 'CHE',
    codigo: '41',
    bandera: 'res://che',
  },
  {
    nombre: 'Surinám',
    name: 'Suriname',
    nom: 'Surinam',
    iso2: 'SR',
    iso3: 'SUR',
    codigo: '597',
    bandera: 'res://sur',
  },
  {
    nombre: 'Svalbard y Jan Mayen',
    name: 'Svalbard and Jan Mayen',
    nom: 'Svalbard et Jan Mayen',
    iso2: 'SJ',
    iso3: 'SJM',
    codigo: '47',
    bandera: 'res://nor',
  },
  {
    nombre: 'Swazilandia',
    name: 'Swaziland',
    nom: 'Swaziland',
    iso2: 'SZ',
    iso3: 'SWZ',
    codigo: '268',
    bandera: 'res://swz',
  },
  {
    nombre: 'Tayikistán',
    name: 'Tajikistan',
    nom: 'Le Tadjikistan',
    iso2: 'TJ',
    iso3: 'TJK',
    codigo: '992',
    bandera: 'res://tjk',
  },
  {
    nombre: 'Tailandia',
    name: 'Thailand',
    nom: 'Thaïlande',
    iso2: 'TH',
    iso3: 'THA',
    codigo: '66',
    bandera: 'res://tha',
  },
  {
    nombre: 'Taiwán',
    name: 'Taiwan',
    nom: 'Taiwan',
    iso2: 'TW',
    iso3: 'TWN',
    codigo: '886',
    bandera: 'res://twn',
  },
  {
    nombre: 'Tanzania',
    name: 'Tanzania',
    nom: 'Tanzanie',
    iso2: 'TZ',
    iso3: 'TZA',
    codigo: '255',
    bandera: 'res://tza',
  },
  {
    nombre: 'Territorio Británico del Océano Índico',
    name: 'British Indian Ocean Territory',
    nom: "Territoire britannique de l'océan Indien",
    iso2: 'IO',
    iso3: 'IOT',
    codigo: '246',
    bandera: 'res://iot',
  },
  {
    nombre: 'Territorios Australes y Antárticas Franceses',
    name: 'French Southern Territories',
    nom: 'Terres australes françaises',
    iso2: 'TF',
    iso3: 'ATF',
    codigo: '',
    bandera: 'res://atf',
  },
  {
    nombre: 'Timor Oriental',
    name: 'East Timor',
    nom: 'Timor-Oriental',
    iso2: 'TL',
    iso3: 'TLS',
    codigo: '670',
    bandera: 'res://tls',
  },
  {
    nombre: 'Togo',
    name: 'Togo',
    nom: 'Togo',
    iso2: 'TG',
    iso3: 'TGO',
    codigo: '228',
    bandera: 'res://tgo',
  },
  {
    nombre: 'Tokelau',
    name: 'Tokelau',
    nom: 'Tokélaou',
    iso2: 'TK',
    iso3: 'TKL',
    codigo: '690',
    bandera: 'res://tkl',
  },
  {
    nombre: 'Tonga',
    name: 'Tonga',
    nom: 'Tonga',
    iso2: 'TO',
    iso3: 'TON',
    codigo: '676',
    bandera: 'res://ton',
  },
  {
    nombre: 'Trinidad y Tobago',
    name: 'Trinidad and Tobago',
    nom: 'Trinidad et Tobago',
    iso2: 'TT',
    iso3: 'TTO',
    codigo: '1 868',
    bandera: 'res://tto',
  },
  {
    nombre: 'Tunez',
    name: 'Tunisia',
    nom: 'Tunisie',
    iso2: 'TN',
    iso3: 'TUN',
    codigo: '216',
    bandera: 'res://tun',
  },
  {
    nombre: 'Turkmenistán',
    name: 'Turkmenistan',
    nom: 'Le Turkménistan',
    iso2: 'TM',
    iso3: 'TKM',
    codigo: '993',
    bandera: 'res://tkm',
  },
  {
    nombre: 'Turquía',
    name: 'Turkey',
    nom: 'Turquie',
    iso2: 'TR',
    iso3: 'TUR',
    codigo: '90',
    bandera: 'res://tur',
  },
  {
    nombre: 'Tuvalu',
    name: 'Tuvalu',
    nom: 'Tuvalu',
    iso2: 'TV',
    iso3: 'TUV',
    codigo: '688',
    bandera: 'res://tuv',
  },
  {
    nombre: 'Ucrania',
    name: 'Ukraine',
    nom: "L'Ukraine",
    iso2: 'UA',
    iso3: 'UKR',
    codigo: '380',
    bandera: 'res://ukr',
  },
  {
    nombre: 'Uganda',
    name: 'Uganda',
    nom: 'Ouganda',
    iso2: 'UG',
    iso3: 'UGA',
    codigo: '256',
    bandera: 'res://uga',
  },
  {
    nombre: 'Uruguay',
    name: 'Uruguay',
    nom: 'Uruguay',
    iso2: 'UY',
    iso3: 'URY',
    codigo: '598',
    bandera: 'res://ury',
  },
  {
    nombre: 'Uzbekistán',
    name: 'Uzbekistan',
    nom: "L'Ouzbékistan",
    iso2: 'UZ',
    iso3: 'UZB',
    codigo: '998',
    bandera: 'res://uzb',
  },
  {
    nombre: 'Vanuatu',
    name: 'Vanuatu',
    nom: 'Vanuatu',
    iso2: 'VU',
    iso3: 'VUT',
    codigo: '678',
    bandera: 'res://vut',
  },
  {
    nombre: 'Venezuela',
    name: 'Venezuela',
    nom: 'Venezuela',
    iso2: 'VE',
    iso3: 'VEN',
    codigo: '58',
    bandera: 'res://ven',
  },
  {
    nombre: 'Vietnam',
    name: 'Vietnam',
    nom: 'Vietnam',
    iso2: 'VN',
    iso3: 'VNM',
    codigo: '84',
    bandera: 'res://vnm',
  },
  {
    nombre: 'Wallis y Futuna',
    name: 'Wallis and Futuna',
    nom: 'Wallis et Futuna',
    iso2: 'WF',
    iso3: 'WLF',
    codigo: '681',
    bandera: 'res://wlf',
  },
  {
    nombre: 'Yemen',
    name: 'Yemen',
    nom: 'Yémen',
    iso2: 'YE',
    iso3: 'YEM',
    codigo: '967',
    bandera: 'res://yem',
  },
  {
    nombre: 'Yibuti',
    name: 'Djibouti',
    nom: 'Djibouti',
    iso2: 'DJ',
    iso3: 'DJI',
    codigo: '253',
    bandera: 'res://dji',
  },
  {
    nombre: 'Zambia',
    name: 'Zambia',
    nom: 'Zambie',
    iso2: 'ZM',
    iso3: 'ZMB',
    codigo: '260',
    bandera: 'res://zmb',
  },
  {
    nombre: 'Zimbabue',
    name: 'Zimbabwe',
    nom: 'Zimbabwe',
    iso2: 'ZW',
    iso3: 'ZWE',
    codigo: '263',
    bandera: 'res://zwe',
  },
];

export class Lista extends GridLayout {
  private list: ListView;
  private item_selecc: any;
  constructor() {
    super();
  }

  initNativeView(): void {
    super.initNativeView();
    this.configGrid();
  }

  onLoaded(): void {
    super.onLoaded();
    if (this.android) {
      const uiModeManager = Application.android.context.getSystemService(android.content.Context.UI_MODE_SERVICE);
      if (uiModeManager != null && uiModeManager.getNightMode() == android.content.res.Configuration.UI_MODE_NIGHT_YES) {
        console.log('El modo oscuro está activado');
      } else {
        console.log('El modo oscuro no está activado');
      }
    } else if (this.ios) {
    }
  }

  private configGrid() {
    this.addRow(new ItemSpec(1, GridUnitType.AUTO));
    this.addRow(new ItemSpec(1, GridUnitType.STAR));
    this.createActionbar();
    this.createLista();
  }

  private createActionbar() {
    const grid: GridLayout = new GridLayout();
    grid.addColumn(new ItemSpec(1, GridUnitType.AUTO));
    grid.addColumn(new ItemSpec(1, GridUnitType.STAR));
    grid.borderBottomWidth = 0.3;
    grid.borderBottomColor = new Color('black');
    const btn: Button = new Button();
    btn.text = 'X';
    btn.fontSize = 20;
    btn.style.background = 'transparent';
    btn.androidElevation = 0;
    btn.col = 0;
    btn.style.fontWeight = 'bold';
    btn.width = 'auto';
    btn.on('tap', (args: EventData) => {
      this.closeModal(this.item_selecc);
    });
    grid.addChild(btn);

    const txt: TextView = new TextView();
    txt.col = 1;
    txt.width = Screen.mainScreen.widthDIPs;
    txt.hint = 'Search';
    txt.borderRadius = 10;
    txt.borderBottomColor = new Color('transparent');
    txt.addEventListener('textChange', (args: EventData) => {
      const textView: TextView = args.object as TextView;
      const nombreABuscar: string = textView.text;
      this.list.items = this.buscarPaises(nombreABuscar);
    });

    grid.addChild(txt);
    grid.row = 0;

    this.addChild(grid);
  }

  private createLista() {
    const grid: GridLayout = new GridLayout();
    grid.addColumn(new ItemSpec(1, GridUnitType.AUTO));
    grid.addColumn(new ItemSpec(1, GridUnitType.STAR));
    this.list = new ListView();
    // list.items=Codigos;
    this.list.items = Codigos;
    this.list.row = 1;
    this.list.rowHeight = 50;
    this.list.itemTemplate = `
      <GridLayout rows="*" columns="auto,auto,auto">
        <Image src="{{bandera}}" width="50" height="auto" decodeHeight="70" marginLeft="5" decodeWidth="70" row="0" col="0" borderRadius="5" horizontalAlignment="left"/>
        <Label text="{{codigo}}" row="0" col="1" horizontalAlignment="left" marginLeft="10" fontWeight="bold"/>
        <Label text="{{name}}" row="0" col="2" horizontalAlignment="left" marginLeft="10" fontWeight="bold"/>
      </GridLayout>
    `;

    this.list.on(ListView.itemTapEvent, (args: ItemEventData) => {
      this.item_selecc = Codigos[args.index];
      this.closeModal(this.item_selecc);
    });
    this.addChild(this.list);
  }

  private buscarPaises(texto) {
    return Codigos.filter((pais) => pais.nombre.toLowerCase().includes(texto.toLowerCase()) || pais.name.toLowerCase().includes(texto.toLowerCase()) || pais.codigo === texto);
  }
}
